# Generated by Django 2.1.2 on 2018-11-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
    ]
